import type { ExchangeId, ExchangeMetadata } from './exchange.types';

export const EXCHANGE_METADATA: Record<ExchangeId, ExchangeMetadata> = {
  upbit: {
    id: 'upbit',
    displayName: '업비트',
    quoteCurrency: 'KRW',
    domestic: true,
    restBaseUrl: 'https://api.upbit.com',
    publicWebSocketUrl: 'wss://api.upbit.com/websocket/v1',
    privateWebSocketUrl: 'wss://api.upbit.com/websocket/v1/private',
    capabilities: [
      'market:list',
      'market:ticker',
      'market:orderbook',
      'market:trades',
      'market:candles',
      'stream:public:ticker',
      'stream:public:orderbook',
      'stream:public:trades',
      'trading:order-chance',
      'trading:create-order',
      'trading:cancel-order',
      'trading:get-order',
      'trading:list-open-orders',
      'trading:list-fills',
      'stream:private:orders',
      'portfolio:balances',
      'portfolio:positions',
      'stream:private:assets',
    ],
  },
  bithumb: {
    id: 'bithumb',
    displayName: '빗썸',
    quoteCurrency: 'KRW',
    domestic: true,
    restBaseUrl: 'https://api.bithumb.com',
    publicWebSocketUrl: 'wss://ws-api.bithumb.com/websocket/v1',
    privateWebSocketUrl: 'wss://ws-api.bithumb.com/websocket/v1/private',
    capabilities: [
      'market:list',
      'market:ticker',
      'market:orderbook',
      'market:trades',
      'market:candles',
      'stream:public:ticker',
      'stream:public:orderbook',
      'stream:public:trades',
      'trading:order-chance',
      'trading:create-order',
      'trading:cancel-order',
      'trading:get-order',
      'trading:list-open-orders',
      'trading:list-fills',
      'stream:private:orders',
      'portfolio:balances',
      'portfolio:positions',
      'portfolio:history',
      'stream:private:assets',
    ],
  },
  coinone: {
    id: 'coinone',
    displayName: '코인원',
    quoteCurrency: 'KRW',
    domestic: true,
    restBaseUrl: 'https://api.coinone.co.kr',
    publicWebSocketUrl: 'wss://stream.coinone.co.kr',
    privateWebSocketUrl: 'wss://stream.coinone.co.kr/v1/private',
    capabilities: [
      'market:list',
      'market:ticker',
      'market:orderbook',
      'market:trades',
      'market:candles',
      'stream:public:ticker',
      'stream:public:orderbook',
      'stream:public:trades',
      'trading:create-order',
      'trading:cancel-order',
      'trading:get-order',
      'trading:list-open-orders',
      'trading:list-fills',
      'stream:private:orders',
      'portfolio:balances',
      'portfolio:positions',
      'portfolio:history',
      'stream:private:assets',
    ],
  },
  korbit: {
    id: 'korbit',
    displayName: '코빗',
    quoteCurrency: 'KRW',
    domestic: true,
    restBaseUrl: 'https://api.korbit.co.kr',
    publicWebSocketUrl: 'wss://ws-api.korbit.co.kr/v2/public',
    privateWebSocketUrl: 'wss://ws-api.korbit.co.kr/v2/private',
    capabilities: [
      'market:list',
      'market:ticker',
      'market:orderbook',
      'market:trades',
      'market:candles',
      'stream:public:ticker',
      'stream:public:orderbook',
      'stream:public:trades',
      'trading:create-order',
      'trading:cancel-order',
      'trading:get-order',
      'trading:list-open-orders',
      'trading:list-fills',
      'stream:private:orders',
      'portfolio:balances',
      'portfolio:positions',
      'portfolio:history',
      'stream:private:assets',
    ],
  },
  binance: {
    id: 'binance',
    displayName: '바이낸스',
    quoteCurrency: 'USDT',
    domestic: false,
    restBaseUrl: 'https://data-api.binance.vision',
    publicRestBaseUrl: 'https://data-api.binance.vision',
    privateRestBaseUrl: 'https://api.binance.com',
    publicWebSocketUrl: 'wss://stream.binance.com:9443',
    referenceOnly: true,
    capabilities: [
      'market:list',
      'market:ticker',
      'market:orderbook',
      'market:trades',
      'market:candles',
      'stream:public:ticker',
      'stream:public:orderbook',
      'stream:public:trades',
      'stream:public:candles',
    ],
  },
};

export const EXCHANGE_METADATA_LIST = Object.values(EXCHANGE_METADATA);
